### PR TITLE
Add screenshots to README

### PR DESCRIPTION
**Pull request by samfreund**
[issue #35 ](https://github.com/BKcore/HexGL/issues/35) was asking for screenshots in the README, so I added some!

### CODE REVIEW

**Review by 3kh0 — CHANGES_REQUESTED** [review]
Where are the screenshots?

**Comment by samfreund** [comment]
I did the editing through the web github, but I think they should be there.  I'm kind of new to pull requests.  I do know that in my fork [HexGL](https://github.com/Sam948-byte/HexGL) they are there, so I might have just messed up forking it.

**Comment by 3kh0** [comment]
I found the screenshots and they are very low quality. Try re-uploading them?

**Comment by Sam948-byte** [comment]
I grabbed them off the internet and blew them up, which is probably why.  I will get bigger ones tomorrow, and upload those.  If I change the branch, would that update what goes through the pull request?

**Comment by samfreund** [comment]
Uploaded new ones, should be good now.

**Comment by 3kh0** [comment]
now they will not show? :(

**Pull request closed without merging**
